name: GitHub Pages

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI SKIP]')"
    # permissions:
    #   contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: ğŸ“… Check date and deactivate cron if necessary
        run: |
          bash ./ci/deactivate.sh "2024-10-20" "gh-pages.yml"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: âš¡ use node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: âš™ï¸ npm setup
        run: npm ci

      - name: â¬‡ï¸ download
        run: |
          bash run.sh

      - uses: EndBug/add-and-commit@v9
        with:
          message: Update download [CI SKIP]
          committer_name: GitHub Actions
          committer_email: action@github.com
